## File generated by the BNF Converter (bnfc 2.9.5).

# Makefile for building the parser and test program.

BNFC       = bnfc
GHC        = ghc
GHC_OPTS   = -Wall
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

TARGETS = interpreter

.PHONY : all clean distclean

# Default goal.

all : ${TARGETS}

# Rules for building the parser.

src/FraJer/%.hs : src/FraJer/%.y
	${HAPPY} ${HAPPY_OPTS} $<

src/FraJer/%.hs : src/FraJer/%.x
	${ALEX} ${ALEX_OPTS} $<

src/FraJer/Abs.hs: src/FraJer.cf
	${BNFC} -d -o src $<

src/FraJer/Lex.hs: src/FraJer/Lex.x
	${ALEX} ${ALEX_OPTS} $<

src/FraJer/Par.hs: src/FraJer/Par.y
	${HAPPY} ${HAPPY_OPTS} $<


src/FraJer/Test : src/FraJer/Abs.hs src/FraJer/Lex.hs src/FraJer/Par.hs src/FraJer/Print.hs src/FraJer/Test.hs
	${GHC} ${GHC_OPTS} $@


interpreter : src/FraJer/Abs.hs src/FraJer/Lex.hs src/FraJer/Par.hs src/FraJer/Print.hs src/TypeChecker.hs src/Executor.hs src/Interpreter.hs
	${GHC} ${GHC_OPTS} -o $@ $^


# Rules for cleaning generated files.

clean :
	-rm -f src/*.hi src/*.o src/*.log src/*.aux src/*.dvi ${TARGETS} src/FraJer/* src/*~ src/*.bak
	-rm -rf src/FraJer

# EOF