-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module FraJer.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified FraJer.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: FraJer.Abs.Ident -> Result
transIdent x = case x of
  FraJer.Abs.Ident string -> failure x

transType :: FraJer.Abs.Type -> Result
transType x = case x of
  FraJer.Abs.TInt -> failure x
  FraJer.Abs.TBool -> failure x

transFType :: FraJer.Abs.FType -> Result
transFType x = case x of
  FraJer.Abs.FTInt -> failure x
  FraJer.Abs.FTBool -> failure x

transVarIdent :: FraJer.Abs.VarIdent -> Result
transVarIdent x = case x of
  FraJer.Abs.Var ident -> failure x

transArrIdent :: FraJer.Abs.ArrIdent -> Result
transArrIdent x = case x of
  FraJer.Abs.Arr ident -> failure x

transDictIdent :: FraJer.Abs.DictIdent -> Result
transDictIdent x = case x of
  FraJer.Abs.Dict ident -> failure x

transFuncIdent :: FraJer.Abs.FuncIdent -> Result
transFuncIdent x = case x of
  FraJer.Abs.Func ident -> failure x

transExpr :: FraJer.Abs.Expr -> Result
transExpr x = case x of
  FraJer.Abs.IE iexpr -> failure x
  FraJer.Abs.BE bexpr -> failure x

transIExpr :: FraJer.Abs.IExpr -> Result
transIExpr x = case x of
  FraJer.Abs.EPlus iexpr1 iexpr2 -> failure x
  FraJer.Abs.EMinus iexpr1 iexpr2 -> failure x
  FraJer.Abs.EDiv iexpr1 iexpr2 -> failure x
  FraJer.Abs.EMul iexpr1 iexpr2 -> failure x
  FraJer.Abs.EMod iexpr1 iexpr2 -> failure x
  FraJer.Abs.ENum integer -> failure x
  FraJer.Abs.EVar varident -> failure x
  FraJer.Abs.EPostInc varident -> failure x
  FraJer.Abs.EPreInc varident -> failure x
  FraJer.Abs.EPostDec varident -> failure x
  FraJer.Abs.EPreDec varident -> failure x
  FraJer.Abs.EArray arrident iexpr -> failure x
  FraJer.Abs.EDict dictident iexpr -> failure x
  FraJer.Abs.EDictB dictident bexpr -> failure x
  FraJer.Abs.EFuncVal funcident args -> failure x

transBExpr :: FraJer.Abs.BExpr -> Result
transBExpr x = case x of
  FraJer.Abs.BTrue -> failure x
  FraJer.Abs.BFalse -> failure x
  FraJer.Abs.BVar varident -> failure x
  FraJer.Abs.BEq iexpr1 iexpr2 -> failure x
  FraJer.Abs.BLeq iexpr1 iexpr2 -> failure x
  FraJer.Abs.BGeq iexpr1 iexpr2 -> failure x
  FraJer.Abs.BLt iexpr1 iexpr2 -> failure x
  FraJer.Abs.BGt iexpr1 iexpr2 -> failure x
  FraJer.Abs.BNeq iexpr1 iexpr2 -> failure x
  FraJer.Abs.BEqB bexpr1 bexpr2 -> failure x
  FraJer.Abs.BNeqB bexpr1 bexpr2 -> failure x
  FraJer.Abs.BNot bexpr -> failure x
  FraJer.Abs.BOr bexpr1 bexpr2 -> failure x
  FraJer.Abs.BAnd bexpr1 bexpr2 -> failure x
  FraJer.Abs.BXor bexpr1 bexpr2 -> failure x
  FraJer.Abs.BArray arrident iexpr -> failure x
  FraJer.Abs.BDict dictident iexpr -> failure x
  FraJer.Abs.BDictB dictident bexpr -> failure x
  FraJer.Abs.BDictHasKey dictident iexpr -> failure x
  FraJer.Abs.BDictHasKeyB dictident bexpr -> failure x
  FraJer.Abs.BFuncVal funcident args -> failure x

transArgs :: FraJer.Abs.Args -> Result
transArgs x = case x of
  FraJer.Abs.ArgsNone -> failure x
  FraJer.Abs.ArgsOne expr -> failure x
  FraJer.Abs.ArgsMany expr args -> failure x

transLambda :: FraJer.Abs.Lambda -> Result
transLambda x = case x of
  FraJer.Abs.Lam ftype params instr -> failure x

transParams :: FraJer.Abs.Params -> Result
transParams x = case x of
  FraJer.Abs.ParamsNone -> failure x
  FraJer.Abs.ParamVar varident type_ -> failure x
  FraJer.Abs.ParamFunc funcident ftype -> failure x
  FraJer.Abs.ParamLambda lambda -> failure x
  FraJer.Abs.ParamVarMany varident type_ params -> failure x
  FraJer.Abs.ParamFuncMany funcident ftype params -> failure x
  FraJer.Abs.ParamLambdaMany lambda params -> failure x

transInstr :: FraJer.Abs.Instr -> Result
transInstr x = case x of
  FraJer.Abs.ISkip -> failure x
  FraJer.Abs.ISeq instr1 instr2 -> failure x
  FraJer.Abs.IIf bexpr instr1 instr2 -> failure x
  FraJer.Abs.IWhile bexpr instr -> failure x
  FraJer.Abs.IFor varident iexpr1 iexpr2 instr -> failure x
  FraJer.Abs.IReturn iexpr -> failure x
  FraJer.Abs.IPrint iexpr -> failure x
  FraJer.Abs.ISwap varident1 varident2 -> failure x
  FraJer.Abs.IBreak iexpr -> failure x
  FraJer.Abs.IBreak1 -> failure x
  FraJer.Abs.IContinue iexpr -> failure x
  FraJer.Abs.IContinue0 -> failure x
  FraJer.Abs.VarDef type_ varident expr -> failure x
  FraJer.Abs.ArrDefInit type_ arrident iexpr expr -> failure x
  FraJer.Abs.ArrDef type_ arrident iexpr -> failure x
  FraJer.Abs.ArrElSet arrident iexpr1 iexpr2 -> failure x
  FraJer.Abs.DictDef type_ dictident -> failure x
  FraJer.Abs.DictElSet dictident iexpr1 iexpr2 -> failure x
  FraJer.Abs.FuncDef ftype funcident params instr -> failure x
  FraJer.Abs.VarAssign varident iexpr -> failure x
  FraJer.Abs.VarAssignPlus varident iexpr -> failure x
  FraJer.Abs.VarAssignMinus varident iexpr -> failure x
  FraJer.Abs.VarAssignMul varident iexpr -> failure x
  FraJer.Abs.VarAssignDiv varident iexpr -> failure x
  FraJer.Abs.VarAssignMod varident iexpr -> failure x
  FraJer.Abs.DebugAssEnable varident -> failure x
  FraJer.Abs.DebugAssDisable varident -> failure x
  FraJer.Abs.DebugReadEnable varident -> failure x
  FraJer.Abs.DebugReadDisable varident -> failure x
